# Project information
site_name: Andrés Matesanz
site_url: https://matesanz.github.io/
site_author: Andrés Matesanz
site_description: >-
  Know more about me on my personal web page.

# Repository
repo_name: Matesanz/Matesanz.github.io
repo_url: https://github.com/Matesanz/Matesanz.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Andrés Matesanz

# Configuration
theme:
  name: material
  icon:
    logo: material/face-man-outline
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top

# Extras
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aimatesanz
      name: Matesanz on Twitter
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
