# Project information
site_name: Andrés Matesanz
site_url: https://matesanz.github.io/
site_author: Andrés Matesanz
site_description: >-
  Know more about me on my personal web page.

# Repository
repo_name: Matesanz/Matesanz.github.io
repo_url: https://github.com/Matesanz/Matesanz.github.io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Andrés Matesanz

# Configuration
theme:
  name: material
  icon:
    logo: material/face-man-outline
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top

# Extras
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aimatesanz
      name: Matesanz on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/matesanz
      name: Matesanz on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aimatesanz/
      name: Matesanz on Linkedin
  analytics:
    provider: google
    property: G-NZQ18ED4V8
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
